<a href="https://colab.research.google.com/github/jinwon1234/aipython/blob/main/20240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
array1 = np.array([np.arange(1,10,2)])
array1

array([[1, 3, 5, 7, 9]])

In [11]:
array2 = np.ones((3,4))
array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
array3 = np.linspace(0,1,10)
array3

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
A.shape

(5, 5)

In [28]:
print(A[3,3])

19


In [38]:
print(A[:2, :2])

[[1 2]
 [6 7]]


In [35]:
print(A[3:,3:])

[[19 20]
 [24 25]]


In [39]:
print(A[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
print(A[:, -2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [45]:
arr = np.arange(1,37)

In [47]:
arr_3d = arr.reshape(3,3,4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [48]:
arr_3d.shape

(3, 3, 4)

In [49]:
arr_34d = arr.reshape(3,4,3)
arr_34d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])